language: generic
sudo: required

install:
  - export ROCK_PATH="$HOME/.rock" # default
  - export PATH="$PATH:./.rock/bin:$ROCK_PATH/bin"
  - export SWIFT_VERSION="3.0.2"
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  #- curl -sL https://raw.githubusercontent.com/vknabel/Rock/master/Scripts/Install.generated.swift | swift -
  #- rock run prepare
  - bundle install
script:
  - set -o pipefail
  - swift test
  #- rock test
  #- rock run lint
  - bundle exec danger
cache:
  - bundler
  - directories:
    - .rock
    - Packages
    - $HOME/.swiftenv
    - $HOME/.rock

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.2
